### ISSUE TITLE
multi instance

### ISSUE THREAD

**Issue by myfrizqi** [joaomirandasa/whats2api#11]
how to use multi instance?

**Comment by impozzible** [comment]
I don't think that's fully integrated now

**Comment by joaomirandasa** [comment]
Best move to use this as multi-instance is running on dockerCompose, you can built your servers and manager them just over docker, more easy and reliable.. If you search for some solution on the same API, sorry i can't provide this now. Best idea is docker-compose.

**Comment by impozzible** [comment]
What are the limitations for not running the multi-instance with docker?

**Comment by joaomirandasa** [comment]
Guys, awesome news, ready for multi instances using docker, please check [MultiInstance](https://github.com/joaomirandasa/whats2api#multiinstances)

**Comment by myfrizqi** [comment]
server API modules (readInstance, reloadServer, etc) not working

**Comment by impozzible** [comment]
Those have been removed from the api I think

**Comment by myfrizqi** [comment]
> Guys, awesome news, ready for multi instances using docker, please check [MultiInstance](https://github.com/joaomirandasa/whats2api#multiinstances)

thanks for the great job
