### ISSUE TITLE
is Posible to set webhook in config via POST Request

### ISSUE THREAD

**Issue by hasanbasri1993** [joaomirandasa/whats2api#13]
Hello.

that my request for update i hope
is Posible to set webhook in config via POST Request?

thanks

**Comment by joaomirandasa** [comment]
I'm expecting include this options on library, but not enough time yet. ASAP when implemented i will let you know.

**Comment by joaomirandasa** [comment]
🎉 Implemented, Check it on [Change Webhook](https://github.com/joaomirandasa/whats2api#change-webhook)
