### ISSUE TITLE
Nothing happens after scanning QR. Getting message in terminal.

### ISSUE THREAD

**Issue by ayushpsc** [joaomirandasa/whats2api#15]
√ Authenticating
√ WAPI Reinjected
√ Whatsapp is ready
!!!!!BROKEN METHODS DETECTED!!!!

Please make a new issue in:

 https://github.com/open-wa/wa-automate-nodejs/issues

with the following title:

BROKEN METHODS:  2.2017.6

Add this to the body of the issue:

 [ 'Store.bp', 'Store.MsgKey' ]

!!!!!BROKEN METHODS DETECTED!!!!

**Comment by joaomirandasa** [comment]
Please update your node modules, run:
 ```npm update ```

If nothing changes please run with super user following command: 
```npm update @open-wa/wa-automate```

Explanation, this happens when whatsapp update his core system for some reason, so you need to keep up to date your methods to work. Best way to make it faster is run over docker.
