### ISSUE TITLE
How check received message

### ISSUE THREAD

**Issue by DeLuca92** [joaomirandasa/whats2api#16]
How I check if people send me any message?
How I check if people send like a "Hi" and the api send Hello (automatic)

**Comment by m7mdcc** [comment]
Using a webhook ,

**Comment by DeLuca92** [comment]
can you explain me better, please?
Can u show a example?
Or What functions I need use ?
Thx

**Comment by joaomirandasa** [comment]
You must to read documentation on README, it's easy to understand, if you're doing this question you dosn't read anything yet, please read before: [SETUP](https://github.com/joaomirandasa/whats2api#setup) 

But if you don't know how to work with webhooks, it's time to google a little.

**Comment by DeLuca92** [comment]
Okay,
Now i can see the received message :).
Every time i receive  a new message  the webhook show me the old message   and the new message .
I will do parser for only show the new message .
