### ISSUE TITLE
Some routes not working. Unable to send messages, set status etc.

### ISSUE THREAD

**Issue by ayushpsc** [joaomirandasa/whats2api#17]
Hi,

Really amazed to see your work. Hats off!!!

I was finally able to run this successfully and tested some routes via postman.

Battery level, getchatbyid, etc worked flawlessly. However, there are some which I would want to use in particular.

I am unable to send message, send files, set status etc. I am getting Response 200 OK and the following :
```
{
    "status": true
}
```
However, none of these requests actually had any effect.

**Comment by ketan1829** [comment]
User should first initiate the message, then this API will work

**Comment by ayushpsc** [comment]
@ketan1829 I tried this with those contacts with whom I have chats already.
Also, this got resolved after removing some request headers that postman was appending while sending the requests. Marking this as closed.
