### ISSUE TITLE
How to send line breaks in messages?

### ISSUE THREAD

**Issue by kingtelecom** [joaomirandasa/whats2api#21]
Do not send \n 
Ex: test\ntest

`<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "localhost:8000/83430/sendMessage?token=j19ksi1mim1lksm12213",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS =>"{\n\t\"phone\":\"55998888888\",\n\t\"body\": \"W2API - Best REST **\n** API for WhatsApp\"\n}",
  CURLOPT_HTTPHEADER => array(
    "Content-Type: application/json"
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;

Return 400: Bad Request
`

**Comment by kmirea** [comment]
CURLOPT_POSTFIELDS should be key value array, curl will convert to json automatically.  also, pretty printed json will be seen as bad in many cases (\n\t)

try CURLOPT_POSTFIELDS => array(
"phone"=>"55998888888",
"body" => "W2API - Best REST \n API for WhatsApp"
),

**Comment by kingtelecom** [comment]
didn't work, same problem

**Comment by joaomirandasa** [comment]
@kingtelecom please go to Discord group. https://discord.gg/nvZ7bx 
I will try to help you.

**Comment by kingtelecom** [comment]
This code work now

`<?php

$url = 'localhost:8000/83430/sendMessage?token=j19ksi1mim1lksm12213';
$data = array("body" => "First**\n**name","phone" => "55998888888");

$postdata = json_encode($data);

$ch = curl_init($url);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $postdata);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));
$result = curl_exec($ch);
curl_close($ch);
print_r ($result);`

Thanks
