### ISSUE TITLE
Request to delete files

### ISSUE THREAD

**Issue by Animeliza** [joaomirandasa/whats2api#22]
I created a function to delete files with a get request

http://127.0.0.1:8000/83430/deleteFile?file=1588894976.jpeg

Inside -> api.js

ROUTE('/{instance}/deleteFile',							deleteFile,			[]);

function deleteFile(){
	var self = this;
	try {
		fs.unlinkSync(F.path.public()+'cdn/'+self.query['file']);
		self.json({status:true});
	  } catch(err) {
		console.error(err)
		self.json({status:false});
	  }
}

**Comment by joaomirandasa** [comment]
You're alredy made it bro, please create a Pull Request of your solicitation and i will implement. You made it. 

thanks in advance.

**Comment by Animeliza** [comment]
OK Pull Request createad.

Thanks bro

**Comment by joaomirandasa** [comment]
@Animeliza It's now implemented. Please check new version. Git clone and try again.
