### ISSUE TITLE
Áudio recebido <data>: undefined

### ISSUE THREAD

**Issue by jersonjunior** [joaomirandasa/whats2api#26]
Percebi que ao receber o áudio o data está indefinido:

`{'messages': [{'id': 'false_55XXXXXXXXXX@c.us_XXXXX', 'body': 'data:audio/ogg; codecs=opus;base64,undefined', 'filelink': None, 'fromMe': False, 'self': 0, 'isForwarded': False, 'author': 'XXXXXXX@c.us', 'time': 1589756239, 'chatId': '55XXXXXXXX@c.us', 'type': 'ptt', 'caption': None, 'quotedMsgBody': None, 'chatName': '+55 XXXXXXXXX'}], 'instanceId': 83430}`

**Comment by joaomirandasa** [comment]
It's a thing related to format of audios be received on instance, i made some changes on code. Please `git clone` and try again.

**Comment by edneijunior** [comment]
estou com o mesmo problema.


data:audio/ogg; codecs=opus;base64,undefined
