### ISSUE TITLE
Docker : setWebhook error 404 Not Found 

### ISSUE THREAD

**Issue by daries** [joaomirandasa/whats2api#28]
I run application with the docker service , send messages success, but for setwebhook there is a 404 not found problem
<img width="976" alt="Screen Shot 2020-05-22 at 14 15 15" src="https://user-images.githubusercontent.com/3004414/82642665-78fa6980-9c38-11ea-8bbe-8c75f5733427.png">
where's the problem? helpme
Thank you.

**Comment by joaomirandasa** [comment]
Sorry about my delay, 

it's version of docker image, i made push of new version - right now available!
