### ISSUE TITLE
BROKEN METHODS DETECTED

### ISSUE THREAD

**Issue by cremiro** [joaomirandasa/whats2api#29]
After scanning the qr, I get this message:

!!!BROKEN METHODS DETECTED!!!

 Please update to the latest version: 1.9.46 2.2021.3

Add this to the body of the issue:
 [ 'Store.WidFactory.createUserWid', 'Store.WidFactory.createWid' ]

!!!!!BROKEN METHODS DETECTED!!!!

**Comment by nestordavalos** [comment]
run npm update

**Comment by joaomirandasa** [comment]
All you need to do is run 
`npm update`

Every time when this appear to you, before open any issue, try update with code above.
