### ISSUE TITLE
sendFile don't work (version 0.0.8)

### ISSUE THREAD

**Issue by dbitencourt** [joaomirandasa/whats2api#30]
Hi, i am not able to send any file using sendFile, even using the link example in the documents. The message after POST is “status:true”, but any file is sent.
Someone have an idea about this problem?

Webhook message is like below:
{"ack":[{"id":"true_552198497xxxx@c.us_3EB0120F98202769298F","chatId":"5521984978804@c.us","status":"viewed"}],"instanceId":83430}
only have "status":"viewed" message,  there isn`t "sent" nor "delivered"

**Comment by nestordavalos** [comment]
version 83 of chrome is not compatible apply in modules/whatsapp.js

browserRevision: "737027", // version 81 chrome

Greetings

**Comment by joaomirandasa** [comment]
Hi guys, sorry about my long delay!

It's now fixed. 
Please promote an `git clone` and try again. 

In advance, welcome to this new world of issues @dbitencourt ! Glad to see you here.
