### ISSUE TITLE
Wrong token authentication on Docker

### ISSUE THREAD

**Issue by indrajatmiko** [joaomirandasa/whats2api#32]
RUN
`> docker build -t joaomirandas/whats2api . `

RUN 
`> docker run --name instance1 -p 8001:8000 joaomirandas/whats2api` AND
`> docker run --name instance2 -p 8002:8000 joaomirandas/whats2api`

both instance1 & instance2 can show on browser and barcode show on http://localhost:8001/instance1/qrcode and http://localhost:8002/instance2/qrcode

when i call via postman 
`http://localhost:8001/instance1/sendMessage?token=j19ksi1mim1lksm12213 AND `
`http://localhost:8002/instance2/sendMessage?token=j19ksi1mim1lksm12213`

```
{
    "status": false,
    "err": "Wrong token authentication"
}
```
No change on config file, any suggest ?

thanks

**Comment by GiancarloJSantos** [comment]
Same error happend here.

**Comment by indrajatmiko** [comment]
> Same error happend here.

have you found solution ?

**Comment by indrajatmiko** [comment]
just update, that fix all. thanks
