### ISSUE TITLE
Cannot send message to unsaved contact

### ISSUE THREAD

**Issue by aRhez0903** [joaomirandasa/whats2api#41]
hello, sorry if i miss the documentation,
but i have problem to send any message to contact who unlisted in my whatsapp contact

sorry for my bad in english

thank before

**Comment by joaomirandasa** [comment]
You must to read section [Security](https://github.com/joaomirandasa/whats2api#security) on README - that's not allowed using this library.

**Comment by aRhez0903** [comment]
Thanks before, now im understand
