### ISSUE TITLE
Wrong token authentication

### ISSUE THREAD

**Issue by rohitarya** [joaomirandasa/whats2api#48]
Everytime i tried to send a messge it is saying wrong token authentication.
{
    "status": false,
    "err": "Wrong token authentication"
}

//WhatsApp Configurations		
instance						: 22139
webhook							: https://villaments.win
token							: j19ksi1mim1lksm12213
masterKey						: w2apiisthebestlibrary

**Comment by wulandrima1** [comment]
npm update

**Comment by rohitarya** [comment]
Thanks its working now
