### ISSUE TITLE
Session is invalid, Retrying

### ISSUE THREAD

**Issue by ketan1829** [joaomirandasa/whats2api#50]
Just after scanning QrCode it shows 

✔️WAPI Reinjected
❌ Session is invalid, Retrying

and then it again restarts the script i guess from starting and again it prompts to scan Qrcode
also shows 

Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed. Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.

**i Tried Updating the Whats2api using**
1. sudo npm i @open-wa/wa-automate
2. sudo npm update @open-wa/wa-automate

**even updated npm , puppeteer and node to latest version**

but it was not updating 

it shows 

Update available 1.9.105 → 2.0.25 
Run npm i @open-wa/wa-automate to update

please , how to fix it

I Appreciate your work 

Thank-you
Ketan

**Comment by lnx1337** [comment]
@ketan1829 Try changing wa-automate dependency in the package.json file
"@open-wa/wa-automate": "2.0.25"

**Comment by ketan1829** [comment]
> @ketan1829 Try changing wa-automate dependency in the package.json file
> "@open-wa/wa-automate": "2.0.25"

Thanks a Lot it worked like a charm for me

thanks a lot i appreciate your response

**Comment by sairmali** [comment]
![Screenshot 2021-12-27 172313](https://user-images.githubusercontent.com/54973008/147469422-96f8ecb0-7df8-41f3-b5de-d99e0d59323f.png)

i am also face same this error after @open-wa/wa-automate": "2.0.25"

please help me
