### ISSUE TITLE
Cant start apps

### ISSUE THREAD

**Issue by vheins** [joaomirandasa/whats2api#60]
Heloo, i cant start whats2api, this screenshoot message

https://prnt.sc/vvgq6p

**Comment by haziqmus** [comment]
same

**Comment by sakidi-umv** [comment]
same

**Comment by rejidan** [comment]
You can try add code 
`Array.prototype.find = function(...args) {
  let index = this.findIndex(...args)
  if (index >= 0) return index >= 0 ? this[index] : void 0
}`
in modules/whatsapp.js before variable global.openWA

![image](https://user-images.githubusercontent.com/6150826/102898890-c378e880-449c-11eb-8431-e8b3bb0dac88.png)

**Comment by smashah** [comment]
@rejidan @haziqmus @aRhez0903 @sakidi-umv Have you lot tried the Easy API CLI in wa-automate?

**Comment by rejidan** [comment]
I haven't tried again to use Easy Api Wa-Automated because when I tried the old version I couldn't take qrcode images yet. I will try again with the latest version, thanks @smashah

**Comment by vheins** [comment]
> @rejidan @haziqmus @aRhez0903 @sakidi-umv Have you lot tried the Easy API CLI in wa-automate?

Thanks you, after post this issue i have try to easy api and its works, but i not close this post hope this repo update

**Comment by smashah** [comment]
Great. Feel free to make an issue in the other repo if there's something I can do there to get this project working for you again 👍
